# Generated by Django 5.0.6 on 2024-05-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mercadopago_customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
