# Generated by Django 5.0.6 on 2024-05-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_mercadopago_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
